spring:
  datasource:
#    url: jdbc:mysql://120.26.51.215:3306/activiti-seed?useUnicode=true&characterEncoding=utf-8&nullCatalogMeansCurrent=true
    url: jdbc:mysql://120.26.51.215:3306/test-act?useUnicode=true&characterEncoding=utf-8&nullCatalogMeansCurrent=true
    username: root
    password: 123456


